server {

    listen 80;
    listen [::]:80;
    server_name login.42.fr;

    # Redirect all traffic to HTTPS.
    return 301 https://$host$request_uri;
}

server {

    # Listen on port 443 for SSL (HTTPS) connections.
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name kpineda-.42.fr;

    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/wordpress;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    # Critical configuration that allows Nginx to communicate with WordPress (FastCGI).
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
    }
}
